C++MakeSignature!
#: File
src .cpp
#: Link args
-largumentsea
-lscok
#: Compiling args
--std=gnu++23 g++
-lscok g++
#: Out
build
#: Project
sender
#: Include
include g++
#: Info
UseCcache
#: Run
#: Compilers filters
.cpp g++